to_do_list/models.py
from to_do_list.extensions import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(60), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    to_do_list = db.relationship('Task', back_populates='author')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    done = db.Column(db.Boolean, default=False)

    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    author = db.relationship('User', back_populates='to_do_list')

to_do_list/__init__.py
from to_do_list.extensions import db, csrf, login_manager
from to_do_list.settings import config
from to_do_list.blueprints.user import user_bp
from to_do_list.blueprints.auth import auth_bp
from to_do_list.models import User, Task
from flask_login import current_user
from flask import Flask
import click
import os

def create_app(config_name=None):

    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')


    app = Flask('to_do_list')
    app.config.from_object(config[config_name])

    init_extensions(app)
    init_blueprints(app)
    register_template_context(app)
    register_command(app)

    return app



def init_extensions(app):
    db.init_app(app)
    csrf.init_app(app)
    login_manager.init_app(app)

def init_blueprints(app):
    app.register_blueprint(user_bp)
    app.register_blueprint(auth_bp)


def register_template_context(app):
    @app.context_processor
    def make_template_context():
        if current_user.is_authenticated:
            active_tasks = Task.query.with_parent(current_user).filter_by(done=False).count()
        else:
            active_tasks = None

        return dict(active_tasks=active_tasks)

def register_command(app):
    @app.cli.command()
    @click.option('--drop', is_flag=True, help='initialize database')
    def initdb(drop):
        if drop:
            click.confirm("This operation will drop all database table, are you sure? ", abort=True)
            db.drop_all()
            click.echo("dropped all tables...")
        db.create_all()
        click.echo("initlized database successful...")

to_do_list/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, request
from to_do_list.models import User, Task
from to_do_list.extensions import db
from faker import Faker
from flask_login import current_user, login_user, logout_user, login_required

auth_bp = Blueprint('auth', __name__)

fake = Faker()


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']

        user = User.query.filter_by(username=username).first()
        if user is not None and user.validate_password(password):
            login_user(user)
            return jsonify(messgae='success')
        return jsonify(message='invalid username'), 400

    return render_template('_login.html')


@auth_bp.route('/register')
def register():
    username = fake.user_name()

    while User.query.filter_by(username=username).first() is not None:
        username = fake.user_name()

    print("-----username: ", username)
    password = fake.word()
    user = User(username=username)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    task_one = Task(body=fake.sentence(), author=user)
    task_two = Task(body=fake.sentence(), author=user)
    task_three = Task(body=fake.sentence(), done=True, author=user)
    task_four = Task(body=fake.sentence(), author=user)

    db.session.add(task_one)
    db.session.add(task_two)
    db.session.add(task_three)
    db.session.add(task_four)
    db.session.commit()




    return jsonify(username=username, password=password)

to_do_list/blueprints/user.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import login_required, current_user
from to_do_list.models import User, Task
from to_do_list.extensions import db

user_bp = Blueprint('user', __name__)


@user_bp.route('/')
def ground():
    return render_template('ground.html')

@user_bp.route('/intro')
def intro():
    return render_template('_intro.html')

@user_bp.route('/index')
@login_required
def index():
    all_count = Task.query.with_parent(current_user).count()
    active_count = Task.query.with_parent(current_user).filter_by(done=False).count()
    completed_count = Task.query.with_parent(current_user).filter_by(done=True).count()
    return render_template('_index.html', tasks=current_user.to_do_list, all_count=all_count,
                           active_count=active_count, completed_count=completed_count)


@user_bp.route('/task/new', methods=['POST'])
@login_required
def task_new():
    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message='invalid task body...'), 400

    task = Task(body=data['body'], author=current_user._get_current_object())
    db.session.add(task)
    db.session.commit()
    return jsonify(html=render_template('_task.html', task=task), message="+1")

@user_bp.route('/item/edit/<int:task_id>', methods=['PUT'])
@login_required
def task_edit(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.author:
        return jsonify(message='permission denied...'), 403

    data = request.get_json()
    if data is None or data['body'].strip() == '':
        return jsonify(message='invalid task body...'), 400

    task.body = data['body']
    db.session.commit()
    return jsonify(message='task updated...')

@user_bp.route('/task/toggle/<int:task_id>', methods=['PATCH'])
@login_required
def task_toggle(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.author:
        return jsonify(message='permission denied...'), 403

    task.done = not task.done
    db.session.commit()
    return jsonify(message='task toggled...')



@user_bp.route('/task/delete/<int:task_id>', methods=['DELETE'])
@login_required
def task_delete(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.author:
        return jsonify(message='permission denied...'), 403
    db.session.delete(task)
    db.session.commit()
    return jsonify(message='delete success')

to_do_list/templates/_index.html
{% extends 'base.html' %}

{% block content %}
    <p>This is the index page that is going to show the list of tasks...</p>

    <header>
        <input id="input-task" data-href="{{url_for('user.task_new') }}"
               type="text" placeholder="what needs to be done? " autocomplete="off" autofocus required>
    </header>



    <div>
        All:<div id="count-all">{{all_count}}</div>
    </div>
    <div>
        Active:<div id="count-active">{{active_count}}</div>
    </div>
    <div>
        Completed:<div id="count-completed">{{completed_count}}</div>
    </div>

    <div class="tasks">
        {% for task in tasks %}
            {% include '_task.html' %}
        {% endfor %}
    </div>
{% endblock %}

to_do_list/templates/_intro.html
{% extends 'base.html' %}

{% block content %}
    This is intro page....
    <a class="btn" href="#login">Get Started</a>
{% endblock %}

to_do_list/templates/_login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Login/Register</h2>
    <div class="form-login">
        <input class="validate input-login" id="input-username" name="username" type="text" placeholder="your username"
               autofocus required>

        <input class="validate input-login" id="input-password" name="password" type="password" placeholder="your password"
               required>

        <button id="btn-register">Get Test Account</button>
        <button id="btn-login">Login</button>
        <button id="btn-toggle-password">Toggle Password</button>
    </div>

{% endblock %}

to_do_list/templates/_task.html
<div class="task" data-done={{task.done|tojson}} data-href="{{url_for('user.task_edit', task_id=task.id) }}"
    data-id="{{task.id}}" data-body="{{task.body}}">
    <div id="body{{task.id}}" class="{%if task.done %}task-done{%else%}task-not-done{% endif %}">
        {{task.body}}
    </div>
    <span>
        <input type="checkbox" class="checkbox-task"  data-href="{{url_for('user.task_toggle', task_id=task.id) }}" {%if task.done %}checked{% endif %}>
    </span>
    <span class="hide task-edit">
        <a class="oi oi-circle-x btn-delete float-right" data-href="{{url_for('user.task_delete', task_id=task.id) }}"></a>
        <a class="oi oi-pencil btn-edit" data-href="{{url_for('user.task_edit', task_id=task.id) }}"></a>
    </span>
</div>

to_do_list/templates/base.html
{% block content %}
{% endblock %}

to_do_list/templates/ground.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bill's To Do List</title>

    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css') }}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='open-iconic-master/font/css/open-iconic-bootstrap.css') }}">
</head>

<body>
    <h1 class="oi oi-shield">This text comes from ground.html </h1>

    <nav>This is the navigation bar...</nav>
    <a href="#intro">Intro</a>
    <a href="#index">Index</a>
    <a href="#login">login</a>
    <hr>

    <div id="main"> </div>

    <script type="text/javascript">
        var csrf_token = "{{csrf_token() }}";
        var intro_page_url = "{{url_for('user.intro') }}";
        var index_page_url = "{{url_for('user.index') }}";
        var task_new_url = "{{url_for('user.task_new') }}";
        var login_url = "{{url_for('auth.login') }}";
        var register_url = "{{url_for('auth.register') }}";
    </script>

</body>

</html>